spring:
  application:
    name: hexagonal-example-cron

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hexagonal;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:

  jpa:
    database: H2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

  # cron 만 부트하는 예제 시나리오를 위한 스키마 선언; application-cron에선 스키마를 관리하지 않아야 한다
  sql:
    init:
      schema-locations: classpath*:schema.sql

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
